
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_HOST: ${HOST_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data_network

  airflow:
    image: apache/airflow:2.7.2-python3.8
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${USER_NAME}:${PASSWORD}@dpg-cqlasntsvqrc738tj7k0-a.oregon-postgres.render.com/{DATABASE_NAME}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    networks:
      - data_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  data_network:
