pipeline_olympics:
  outputs:
    dev:
      dbname: mydatabase_r7dp_1c3c
      host: dpg-cr94e5jtq21c73a3oqmg-a.oregon-postgres.render.com
      pass: VQq4VidWznxZo2umGSL592TfSYNP32F6
      port: 5432
      schema: olympics
      threads: 1
      type: postgres
      user: herbertsouto
  target: dev