# Nome do projeto e versão
name: 'pipeline_olympics'
version: '1.0.0'

# Perfil utilizado para este projeto
profile: 'pipeline_olympics'

# Caminhos para os diferentes tipos de arquivos
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Limpeza dos diretórios especificados ao rodar dbt clean
clean-targets:
  - "target"
  - "dbt_packages"

# Configurações de modelos
models:
  pipeline_olympics:
    # Configuração dos modelos na pasta 'staging'
    staging:
      +materialized: view
      +docs:
        node_color: "#CD7F32"

    # Configuração dos modelos na pasta 'intermediate'
    intermediate:
      +materialized: view
      +docs:
        node_color: "#C0C0C0"

    # Configuração dos modelos na pasta 'marts'
    marts:
      +materialized: table
      +docs:
        node_color: "#FFD700"
